### ISSUE TITLE
[FR] Add Bootloader ID

### ISSUE THREAD

**Issue by NicoHood** [volium/nanoBoot#5]
The Lufa CDC Bootloader has some additional data at the end of the flash to identify the bootloader type as well as its size. With the current setup we can at least add a type indicator, but the bootloader size will not fit. But those can be read from the fuses itself and are more accurate, if i am not wrong.

https://github.com/abcminiuser/lufa/blob/master/Bootloaders/CDC/BootloaderAPITable.S#L84
https://github.com/abcminiuser/lufa/blob/master/Bootloaders/CDC/BootloaderCDC.txt#L186

I am currently creating a simpler dmbs makefile for this project (which should also work for #1 @osamuaoki if I am not wrong), PR will follow:
https://github.com/abcminiuser/dmbs

**Comment by volium** [comment]
> ... those can be read from the fuses itself and are more accurate, if i am not wrong.

Yes, that's true, I'm not very worried about that part I guess. Ideally, I'd love to see this integrated into AVRDUDE itself, though.

**Comment by NicoHood** [comment]
Another idea I had for the left 4 bytes: It does not seem that your code checks the flash limit. So it could potentially overwrite itself. If it fits into 4 bytes, you could check that also. Might be tricky though. Otherwise You'd have to carefully check in the host application.

Or a [two way reset mechanism](https://github.com/NicoHood/HoodLoader2/wiki/How-to-use-reset) would be nice. However that takes way too much code I guess.

I looked through the code and did not find something obviously wrong/unoptimized. You said in the readme that there is still potential. Any ideas where to start?

**Comment by volium** [comment]
I know it has been a really long time since your last comment, but I just merged @osamuaoki's changes. You may want to go through those commits to see some of his improvements, most are related to branch optimizations, and hiding one extra instruction (2 bytes) in one of the ISR Vectors, USB_General_Vector specifically.

**Comment by volium** [comment]
Hello @NicoHood, just wanted to let you know that I have merged two of @sigprof's PR, and one of them includes the check to avoid overwriting the bootloader (which you had mentioned earlier). We currently have 6 bytes left, but I know @sigprof has found a few more ways to free up more space, hopefully those can be merged at some point in the near future.
