### ISSUE TITLE
Q on security

### ISSUE THREAD

**Issue by 3DTek-xyz** [volium/nanoBoot#6]
The original LUFA source for HID bootloader suggests
"warning <b>THIS BOOTLOADER IS NOT SECURE.</b> Malicious entities can recover written data, even if the device  lockbits are set."
Being that you have built with LUFA as a start/reference, does this statement still apply?

**Comment by volium** [comment]
Hello @3DTek-xyz, sorry for not getting back to you earlier on this.

What you mention above is probably also true for nanoBoot, the firmware is very very tight as it is, so there's no actual space to even try to mitigate this issue, and even then, with the right tools, a bad actor could recover written data (ie. via man-in-the-middle attack) or by causing a glitch that could bypass the fusses.
